# The [interfaces] section can be used to define the ingress/egress interfaces
# and their streams. Its format is the following:
# iface_custom_name = type param1=value1 param2=value2
# For ingress interfaces, the must have a stream list.
# This can be defined as iface_custom_name:streams = stream1 stream2 stream3...
# An ingress packet will be triet to match by each stream (in the order they defined in the list)
# If no match, it will be dropped

[interfaces]
uni = eth iface=swp2
uni:streams = stream_uni
# Here we use DetNet pseudowires, so packets sent over UDP tunnels with MPLS DetNet control word
# encapsulation. Destination UDP port is optional, the standardized 6635 used if not given.
# As one can notice, the same stream applied to both ingress NNI interface since we expect the same
# encapsulation for each packet regardless which NNI received it.
nni1_in = udp-in iface=swp0 ipv=4
nni1_in:streams = stream_nni
nni2_in = udp-in iface=swp1 ipv=4
nni2_in:streams = stream_nni
# As one can notice, nni1_out and nni2_out are only egress interfaces,
# So they cant used to receive packets. Therefore no :streams list definition necessary.
# The UDP source port is optional, the standardized 6635 used if not given.
nni1_out = udp-out iface=swp0 dstip=192.168.55.1
nni2_out = udp-out iface=swp1 dstip=192.168.66.1


# In the [objects] section we have the stateful packet processing information.
# These object can be used as parameters of actions in the pipelines.
# The same object can be used in multiple pipelines as well.
# Every object has a type, it is possible to define multiple action with the same type,
# however they has to hav different names e.g.
# seqgen1 = SeqGen
# seqgen2 = SeqGen
# another_seqgen = SeqGen
# They have their own internal states
# The formet looks like the following:
# obj_name = type param1=val1 param2=val2...
# (the type is mandatory, parameters might have or not, depends on the action)
[objects]
# SeqGen generate seqence number every time when it executed in the pipeline.
# This sequence number will be set to that packet, but NOT WRITTEN INTO ANY HEADER by default.
# The rationale behind this behavior: a sequence number can be used in different parts of the pipeline,
# and for both TSN R-tag and DetNet d-CW, its format depends on the heade used. Also one can generate a
# seqence number, but that used on different branches of the pipeline.
# For example, if a pipeline have 3 branches, each with different encapsulation, it only makes sense to
# generate the sequence number early, since if they generated on the branches, each branch will increase the
# internal state sequence number, resulting undefined behavior

# SeqRcvy is used at the elimination side. Its working with sequence number of the packet, so before
# a SeqRcvy object used in the action pipeline, the packet MUST HAVE SEQUENCE NUMBER.
# This will be obtained from the sequenced header like rtag or dcw with the "readseq HEADERNAME" action.
# SeqRcvy drop every replica of the packet, except the first one.

# We use the prf and pef names here, referring to the Packet Elimination/Replication Functions
# which will use these objects for their operation.
prf = SeqGen InitSeqStart=0
pef = SeqRcvy


# Here the [streams] defined, they each have three set of settings as definition:
# :packet - header structure (until we interested)
# :match - matching on header fields for packet identification. Multiple headers and fields can be matched
# :actions - pipeline definition. List of actions executed sequentially.
# The actions in the list separated by commas, they might have parameters as well.
# Some actions can use objects as their parameters and some objects are implicitly recognized as actions
# like seq_gen or seqrcvy below. They can be written as "seqgen seq_gen" and "eliminate seqrcvy" as well.
[streams]
stream_uni:packet = eth, cvlan
stream_uni:match = cvlan vid=0
stream_uni:actions = prf, edit cvlan.vid=99, before eth add mpls, after mpls add dcw, writeseq dcw, replicate nni1_out nni2_out

# The MPLS Bottom of Stack bit (mpls.bos=1) must be set on the innermost MPLS label.
# This helps Wireshark to decode the protocols properly after the MPLS label.
nni1_out = edit mpls.label=100 mpls.bos=1, send nni1_out
nni2_out = edit mpls.label=200 mpls.bos=1, send nni2_out

stream_nni:packet = mpls, dcw, eth, cvlan
stream_nni:match = cvlan vid=99
stream_nni:actions = readseq dcw, pef, del dcw, del mpls, del cvlan, send uni
