
variables:
  IMAGE_NAME: r2dtwo-ci
  IMAGE_VERSION: v3


# run on the main branch, from web, for merge requests
#   only run for feature branch commits when there is no associated merge request
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always


stages:
  - build-image
  - verify
  - build
  - test


verify-ci-config:
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  stage: verify
  tags:
    - tsn
  script:
    - .gitlab-ci/verify_yaml.pl


# this Docker image should contain everything we need
# image: ${IMAGE_NAME}:${IMAGE_VERSION}
build-docker-image:
  stage: build-image
  image:
    name: docker:29.0.0-cli
  services:
    - name: docker:29.0.0-dind
  tags:
    - tsn-shell
  before_script:
    - docker info
  script:
    - docker build . -t ${IMAGE_NAME}:${IMAGE_VERSION} -f .gitlab-ci/Dockerfile
  rules:
    - changes:
      - .gitlab-ci/Dockerfile


build-r2dtwo-debug:
  stage: build
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  tags:
    - tsn
  script:
    - CC=gcc make debug -j
  artifacts:
    paths:
      - r2dtwo

build-r2dtwo-release:
  stage: build
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  tags:
    - tsn
  script:
    - CC=gcc make release -j

build-r2dtwo-debug-cpp:
  stage: build
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  tags:
    - tsn
  script:
    - .gitlab-ci/cppize.pl Makefile > Makefile-cpp
    - make debug -j -f Makefile-cpp

build-r2dtwo-release-cpp:
  stage: build
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  tags:
    - tsn
  script:
    - .gitlab-ci/cppize.pl Makefile > Makefile-cpp
    - make release -j -f Makefile-cpp

build-r2dtwo-debug-clang:
  stage: build
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  tags:
    - tsn
  script:
    - CC=clang make debug -j

build-r2dtwo-release-clang:
  stage: build
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  tags:
    - tsn
  script:
    - CC=clang make release -j


build-unit_test:
  stage: build
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  tags:
    - tsn
  script:
    - cd unit_test
    - mkdir build
    - cd build
    - cmake ..
    - make -j
  artifacts:
    paths:
      - unit_test/build/test_*

build-unit_test_asan:
  stage: build
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  tags:
    - tsn
  script:
    - cd unit_test
    - mkdir build
    - cd build
    - cmake .. -DUSE_ASAN=yes
    - make -j
  artifacts:
    paths:
      - unit_test/build/test_*


.pytest.common:
  stage: test
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  tags:
    - tsn
  dependencies:
    - build-r2dtwo-debug
  retry: 2
  allow_failure: false
  script:
    - cd test
    - python3 -m $TESTNAME

pytest_oam:
  extends: .pytest.common
  variables:
    TESTNAME: oam.oam

pytest_oam_tsn:
  extends: .pytest.common
  variables:
    TESTNAME: oam_tsn.oam_tsn

pytest_oam_srv6:
  extends: .pytest.common
  variables:
    TESTNAME: oam_srv6.oam_srv6

pytest_notification_tsn:
  extends: .pytest.common
  variables:
    TESTNAME: notification.notification

pytest_notification_detnet:
  extends: .pytest.common
  variables:
    TESTNAME: notification.notification-detnet

pytest_elimination:
  extends: .pytest.common
  variables:
    TESTNAME: sequence.sequence

pytest_match:
  extends: .pytest.common
  variables:
    TESTNAME: match.match

pytest_mask:
  extends: .pytest.common
  variables:
    TESTNAME: mask.mask

pytest_pof:
  extends: .pytest.common
  variables:
    TESTNAME: pof.pof

pytest_delay:
  extends: .pytest.common
  variables:
    TESTNAME: delay.delay

pytest_stress:
  extends: .pytest.common
  variables:
    TESTNAME: stress.stress_ping

pytest_srv6:
  extends: .pytest.common
  variables:
    TESTNAME: srv6.srv6


.unit_test.common:
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  stage: test
  tags:
    - tsn
  dependencies:
    - build-unit_test
  script:
    - TEST_COLOR=1 valgrind --error-exitcode=42 --leak-check=full unit_test/build/$TESTNAME

unit_test.conf_utils:
  extends: .unit_test.common
  variables:
    TESTNAME: test_conf_utils

unit_test.delay:
  extends: .unit_test.common
  variables:
    TESTNAME: test_delay

unit_test.header_api:
  extends: .unit_test.common
  variables:
    TESTNAME: test_header_api

unit_test.header_compare:
  extends: .unit_test.common
  variables:
    TESTNAME: test_header_compare

unit_test.header_read:
  extends: .unit_test.common
  variables:
    TESTNAME: test_header_read

unit_test.header_write:
  extends: .unit_test.common
  variables:
    TESTNAME: test_header_write

unit_test.if_utils:
  extends: .unit_test.common
  variables:
    TESTNAME: test_if_utils

unit_test.inet_utils:
  extends: .unit_test.common
  variables:
    TESTNAME: test_inet_utils

unit_test.packet:
  extends: .unit_test.common
  variables:
    TESTNAME: test_packet

unit_test.seq_gen:
  extends: .unit_test.common
  variables:
    TESTNAME: test_seq_gen

unit_test.seq_rcvy_match:
  extends: .unit_test.common
  variables:
    TESTNAME: test_seq_rcvy_match

unit_test.seq_rcvy_oam:
  extends: .unit_test.common
  variables:
    TESTNAME: test_seq_rcvy_oam

unit_test.seq_rcvy_seamless:
  extends: .unit_test.common
  variables:
    TESTNAME: test_seq_rcvy_seamless

unit_test.seq_rcvy_vector:
  extends: .unit_test.common
  variables:
    TESTNAME: test_seq_rcvy_vector

unit_test.thread:
  extends: .unit_test.common
  variables:
    TESTNAME: test_thread

unit_test.time:
  extends: .unit_test.common
  variables:
    TESTNAME: test_time

unit_test.utils:
  extends: .unit_test.common
  variables:
    TESTNAME: test_utils


# we need to run these separately because valgrind has no concurrency
.multithread_unit_test.common:
  image: ${IMAGE_NAME}:${IMAGE_VERSION}
  stage: test
  tags:
    - tsn
  dependencies:
    - build-unit_test_asan
  script:
    - TEST_COLOR=1 unit_test/build/$TESTNAME

multithread_unit_test.delay:
  extends: .multithread_unit_test.common
  variables:
    TESTNAME: test_delay

multithread_unit_test.seq_rcvy_match:
  extends: .multithread_unit_test.common
  variables:
    TESTNAME: test_seq_rcvy_match

multithread_unit_test.seq_rcvy_oam:
  extends: .multithread_unit_test.common
  variables:
    TESTNAME: test_seq_rcvy_oam

multithread_unit_test.seq_rcvy_vector:
  extends: .multithread_unit_test.common
  variables:
    TESTNAME: test_seq_rcvy_vector

