#TODO we should be using cmake

CC = gcc
#TODO valgrind 3.19 cannot yet read DWARF5 generated by clang 14
# CC = clang -gdwarf-4
CFLAGS += -g -O0 -std=gnu99
#TODO clang ignores -Wmissing-declarations
CFLAGS += -Wall -Wextra -Wshadow -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings
CFLAGS += -Werror
CFLAGS += -Iinifile
CFLAGS += -DVERBOSE_RECV
CFLAGS += -DVERBOSE_CONF

#TODO gnu libc doesn't need this
LFLAGS += -lpthread

OBJECTS = main.o action.o delay.o header.o interface.o packet.o parsetree.o pipeline.o protocol.o utils.o
OBJECTS += if_eth.o if_internal.o if_ip.o if_udp_in.o if_udp_out.o if_utils.o
OBJECTS += seq_gen.o seq_recov.o pof.o
OBJECTS += configfile.o conf_actions.o conf_interface.o conf_object.o conf_packet.o conf_streams.o conf_utils.o
OBJECTS += inifile/hashmap.o inifile/inifile.o

HEADERS = action.h delay.h header.h interface.h packet.h parsetree.h pipeline.h protocol.h utils.h
HEADERS += time_utils.h
HEADERS += if_eth.h if_internal.h if_ip.h if_udp_in.h if_udp_out.h if_utils.h
HEADERS += seq_gen.h seq_recov.h pof.h
HEADERS += configfile.h conf_actions.h conf_interface.h conf_object.h conf_packet.h conf_streams.h conf_utils.h
HEADERS += inifile/hashmap.h inifile/inifile.h inifile/iniutils.h

EXE = r2dtwo

default: $(EXE)

inifile/%.o : inifile/%.c $(HEADERS)
	cd inifile && $(CC) $(CFLAGS) -c $(<F)

%.o : %.c $(HEADERS)
	$(CC) $(CFLAGS) -c $<

$(EXE): $(OBJECTS)
	$(CC) $^ -o $@ $(LFLAGS)

install: $(EXE)
	cp $(EXE) /usr/local/bin

.PHONY: clean
clean:
	rm -f *.o
	rm -f inifile/*.o
	rm -f $(EXE)

