#TODO we should be using cmake

#TODO valgrind 3.19 cannot yet read DWARF5 generated by clang 14
#CC = clang -gdwarf-4

CFLAGS += -g -std=gnu99

#TODO clang ignores -Wmissing-declarations
CFLAGS += -Wall -Wextra -Wshadow -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wvla -Wc++-compat
CFLAGS += -Werror
CFLAGS += -Iinifile
CFLAGS += -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3
#CFLAGS += -fanalyzer

# ASan is incompatible with Valgrind
#CFLAGS += -fsanitize=address
#LFLAGS += -lasan

LFLAGS += -lm
#TODO gnu libc doesn't need this
LFLAGS += -lpthread

OBJECTS = main.o action.o delay.o header.o interface.o object.o packet.o parsetree.o pipeline.o protocol.o state.o
OBJECTS += log.o inet_utils.o thread_utils.o utils.o
OBJECTS += if_eth.o if_internal.o if_ip.o if_oam.o if_oam_cmd.o if_udp_in.o if_udp_out.o if_utils.o
OBJECTS += pof.o replicate.o seq_gen.o seq_recov.o
OBJECTS += oam_command.o oam_core.o oam_message.o oam_request.o
OBJECTS += json.o
OBJECTS += configfile.o conf_actions.o conf_interface.o conf_object.o conf_packet.o conf_streams.o conf_oam.o conf_utils.o
OBJECTS += inifile/hashmap.o inifile/inifile.o

HEADERS = action.h delay.h header.h interface.h object.h packet.h parsetree.h pipeline.h protocol.h state.h value.h
HEADERS += log.h inet_utils.h thread_utils.h time_utils.h utils.h version.h
HEADERS += if_eth.h if_internal.h if_ip.h if_udp_in.h if_udp_out.h if_utils.h if_oam.h if_oam_cmd.h
HEADERS += seq_gen.h seq_recov.h pof.h replicate.h
HEADERS += oam.h oam_command.h oam_core.h oam_message.h oam_request.h
HEADERS += json.h
HEADERS += configfile.h conf_actions.h conf_interface.h conf_object.h conf_packet.h conf_streams.h conf_oam.h conf_utils.h
HEADERS += inifile/hashmap.h inifile/inifile.h inifile/iniutils.h

EXE = r2dtwo

default: release

__rel:
	$(eval CFLAGS += -O2)

release: __rel $(EXE)

#support both gdb and uftrace
__deb:
	$(eval CFLAGS += -O0 -pg -ggdb)

debug: __deb $(EXE)


inifile/%.o : inifile/%.c $(HEADERS) Makefile
	cd inifile && $(CC) $(CFLAGS) -c $(<F)

%.o : %.c $(HEADERS) Makefile
	$(CC) $(CFLAGS) -c $<

$(EXE): $(OBJECTS)
	$(CC) $^ -o $@ $(LFLAGS)

install: $(EXE)
	cp $(EXE) /usr/local/bin

.PHONY: clean
clean:
	rm -f *.o
	rm -f inifile/*.o
	rm -f $(EXE)

.PHONY: doc
doc:
	-rm /tmp/r2dtwo.md
	cat doc/getting_started/README.md >> /tmp/r2dtwo.md
	cat doc/getting_started/scenario1/README.md >> /tmp/r2dtwo.md
	cat doc/getting_started/scenario2/README.md >> /tmp/r2dtwo.md
	cat doc/getting_started/scenario3/README.md >> /tmp/r2dtwo.md
	cat doc/logging.md >> /tmp/r2dtwo.md
	cat doc/oam.md >> /tmp/r2dtwo.md
	cat doc/inispec.md >> /tmp/r2dtwo.md
	doc/protocolfields.pl protocol.c > doc/protocols.md
	cat doc/protocols.md >> /tmp/r2dtwo.md
	#cat doc/stream_compiler.md >> /tmp/r2dtwo.md
	pandoc --toc --pdf-engine=xelatex -V 'monofontoptions: Color=0070c0,Scale=0.7' \
		-V monofont="Noto Sans Mono" -V fontsize=12pt -V geometry:margin=1.5cm /tmp/r2dtwo.md -o readme.pdf
