#TODO we should be using cmake

CC = gcc
#TODO valgrind 3.19 cannot yet read DWARF5 generated by clang 14
#CC = clang -gdwarf-4
CFLAGS += -g -O0 -std=gnu99
#TODO clang ignores -Wmissing-declarations
CFLAGS += -Wall -Wextra -Wshadow -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings
CFLAGS += -Werror
CFLAGS += -Iinifile

LFLAGS += -lm
#TODO gnu libc doesn't need this
LFLAGS += -lpthread

OBJECTS = main.o action.o delay.o header.o interface.o log.o oam.o object.o packet.o parsetree.o pipeline.o protocol.o utils.o
OBJECTS += if_eth.o if_internal.o if_ip.o if_oam.o if_oam_cmd.o if_udp_in.o if_udp_out.o if_utils.o
OBJECTS += pof.o replicate.o seq_gen.o seq_recov.o
OBJECTS += json.o
OBJECTS += configfile.o conf_actions.o conf_interface.o conf_object.o conf_packet.o conf_streams.o conf_oam.o conf_utils.o
OBJECTS += inifile/hashmap.o inifile/inifile.o

HEADERS = action.h delay.h header.h interface.h log.h oam.h object.h packet.h parsetree.h pipeline.h protocol.h utils.h value.h
HEADERS += time_utils.h version.h
HEADERS += if_eth.h if_internal.h if_ip.h if_udp_in.h if_udp_out.h if_utils.h if_oam.h if_oam_cmd.h
HEADERS += seq_gen.h seq_recov.h pof.h replicate.h
HEADERS += json.h
HEADERS += configfile.h conf_actions.h conf_interface.h conf_object.h conf_packet.h conf_streams.h conf_oam.h conf_utils.h
HEADERS += inifile/hashmap.h inifile/inifile.h inifile/iniutils.h

EXE = r2dtwo

default: $(EXE)

inifile/%.o : inifile/%.c $(HEADERS) Makefile
	cd inifile && $(CC) $(CFLAGS) -c $(<F)

%.o : %.c $(HEADERS) Makefile
	$(CC) $(CFLAGS) -c $<

$(EXE): $(OBJECTS)
	$(CC) $^ -o $@ $(LFLAGS)

install: $(EXE)
	cp $(EXE) /usr/local/bin

.PHONY: clean
clean:
	rm -f *.o
	rm -f inifile/*.o
	rm -f $(EXE)

.PHONY: doc
doc:
	-rm /tmp/r2dtwo.md
	cat doc/getting_started/README.md >> /tmp/r2dtwo.md
	cat doc/getting_started/scenario1/README.md >> /tmp/r2dtwo.md
	cat doc/getting_started/scenario2/README.md >> /tmp/r2dtwo.md
	cat doc/getting_started/scenario3/README.md >> /tmp/r2dtwo.md
	cat doc/inispec.md >> /tmp/r2dtwo.md
	doc/protocolfields.pl protocol.c > doc/protocols.md
	cat doc/protocols.md >> /tmp/r2dtwo.md
	#cat doc/stream_compiler.md >> /tmp/r2dtwo.md
	pandoc --pdf-engine=xelatex -V monofont="Noto Sans Mono" -V fontsize=10pt -V geometry:margin=1.5cm /tmp/r2dtwo.md -o readme.pdf
