// Copyright (c) 2023-2025, Ericsson AB and Ericsson Telecommunication Hungary
// All rights reserved.


#ifndef R2_OAM_H
#define R2_OAM_H

#include "interface.h"
#include "object.h"
#include "pipeline.h"
#include "hashmap.h"

#define OAM_CFM_REQUEST_OPCODE 128
#define OAM_CFM_RESPONSE_OPCODE 129

#define SEQ_IS_OAM(seq)     \
    (ntohl(seq) & 0x10000000u)

// public interface of the OAM module

enum OAM_MP_Type { OAM_Start, OAM_Stop, OAM_Intermediate };

enum OAM_MP_Encap { OAM_PW, OAM_TSN, OAM_SRv6 };

enum OAM_MP_Addr_Source { OAM_FROM_Unknown, OAM_FROM_Edit, OAM_FROM_Match, OAM_FROM_Later, OAM_FROM_Default };

// state object for a pipeline action that sends/receives OAM packets
struct OAM_MaintenancePoint;

// represents one address for message injection into the pipeline
struct OAM_MP_Address {
    char *header;
    char *field;
    struct Value val; // must be a constant value
    enum OAM_MP_Addr_Source source;
    struct OAM_MP_Address *next;
};

const char *oam_mp_type_to_str(enum OAM_MP_Type type);

const char *oam_mp_encap_to_str(enum OAM_MP_Encap encap);

const char *oam_mp_addr_source_to_str(enum OAM_MP_Addr_Source src);

// initialize the OAM module
// the node id in the generated OAM messages is a hash of the hostname
// use a non-NULL @override_hostname to set a different name
// useful in mininet, where all nodes have the same hostname (no UTS namespace isolation)
// @returns true on success
bool init_oam(const char *override_hostname);

// stops the OAM module and cleans up its resources
void finish_oam(void);

// receive on the action pipeline
// keeps hold of @pi, the action should return ACR_HOLD
void oam_receive_inband(struct OAM_MaintenancePoint *mp, struct PipelineIterator *pi);

// receive on a return interface
// makes a copy of @message
void oam_receive_outofband(struct Interface *iface, const char *message);

// receive connection on the command (telnet) interface
void oam_start_command_connection(int fd, const char *remote_ip, unsigned short remote_port);

// print an alert message to all active command sessions (like wall(1) does)
void oam_cli_alert(const char *fmt, ...)
    __attribute__((format(printf, 1, 2)))
    __attribute__((nonnull(1)));

// creates a maintenance point or adds reference to an existing one
// @returns pointer to the MP
// MPs are uniquely identified by @mp_name
// when multiple actions refer to the same MP the @stream_name, @type and @level must be the same
// MP can be bound to a pipeline object @obj to monitor its state
// @protostack determines the encapsulation of the MP
// if MP is an injector point (OAM_Start, OAM_Intermediate), @pipe and @idx define the injection point
// @addr specifies the addressing for the injected messages
struct OAM_MaintenancePoint *oam_new_maintenance_point(const char *stream_name, const char *mp_name,
        enum OAM_MP_Type type, unsigned level,
        const enum ProtocolID *protostack,
        struct PipelineObject *obj, struct Pipeline *pipe, unsigned idx,
        struct OAM_MP_Address *addr);

// removes a reference from @mp
// @mp is deleted when its reference count reaches zero
void oam_unref_maintenance_point(struct OAM_MaintenancePoint *mp);

// notify OAM about the deletion of @pipe so MPs don't want to inject into it
// note: it might happen that some MPs won't be able to send after this
void oam_pipeline_deleted(struct Pipeline *pipe);

// MP has counter for non-OAM packets
void oam_mp_count_data_packet(struct OAM_MaintenancePoint *mp, unsigned len);

// @returns the canonical name for an automatically generated MIP
// the return value is a dynamically allocated string
char *oam_automip_name(const char *stream, unsigned level, const char *object_name, bool post);

// @returns true if @name looks like an autogenerated MIP name
// see @oam_automip_name
// @position can be used to filter the MIP type:
//      <0 only accepts pre-MIP
//      >0 only accepts post-MIP
//      =0 accepts both
bool oam_is_automip_name(const char *name, int position);

// start sending mask signal periodically
// @mip_name should be a post-AutoMIP of a SequenceRecovery object
void oam_automip_start_mask_session(const char *mip_name);

// stop the mask signal session
// @mip_name should be a post-AutoMIP of a SequenceRecovery object
void oam_automip_stop_mask_session(const char *mip_name);

// specify the command interface that receives telnet connections
// there can only be one command interface
// see @oam_start_command_connection
bool set_oam_cmd_if(struct Interface *iface);

// registers an oam return interface that receives out-of-band replies
// there can be several return interfaces
// see @oam_recv_reply
void add_oam_if(struct Interface *iface);

// start an infinitely running OAM ping session
// it runs in the background, i.e. it is not associated with a telnet session
bool oam_start_background_ping(const char *name, const char *command);

// decode the DetNet Associated Channel Header (PROTO_ID_OAM)
#define INTERPRET_DACH(header)                                                      \
    struct {                                                                        \
        unsigned char version;                                                      \
        unsigned char seq;                                                          \
        unsigned short channel;                                                     \
        unsigned int nodeid;                                                        \
        unsigned char level;                                                        \
        unsigned char flags;                                                        \
        unsigned char session;                                                      \
    } dach;                                                                         \
    dach.version = (header)[0] & 0xf;                                               \
    dach.seq = (header)[1];                                                         \
    dach.channel = ((header)[2] << 8) + ((header)[3]);                              \
    dach.nodeid = ((header)[4] << 12) + ((header)[5] << 4) + ((header)[6] >> 4);    \
    dach.level = ((header)[6] >> 1) & 0x7;                                          \
    dach.flags = (((header)[6] & 0x1) << 4) + ((header)[7] >> 4);                   \
    dach.session = ((header)[7] & 0xf)

//TODO functions to set the dACH fields


#endif // R2_OAM_H
