
[interfaces]

ifA = eth iface=ethBA
ifA:streams = s1
ifC = eth iface=ethBC
ifC:streams = s2

[streams]

s1:packet = eth, cvlan          ; now we can have comments at the end
s1:match = cvlan vid=1001       # both start characters are supported
s1:actions = edit cvlan.vid=2023, send ifC
#send ifC, add before cvlan svlan_new pcp=3 vid=2000 , add after cvlan rtag seq=0x0800abcd , edit cvlan.pcp=2, del cvlan , send ifC

s2:packet = eth , cvlan
s2:match = cvlan vid=2023
s2:actions = del cvlan, after eth add cvlan vid=1001, send ifA

