
[interfaces]

ifA = type=eth iface=ethBA
ifC = type=eth iface=ethBC

[streams]

s1:iface = ifA
s1:packet = eth ; cvlan vid=1001
s1:actions = edit cvlan.vid=2023 ; send ifC
#send ifC; add before cvlan svlan_new pcp=3 vid=2000 ; add after cvlan rtag seq=0x0800abcd ; edit cvlan.pcp=2; del cvlan ; send ifC

s2:iface = ifC
s2:packet = eth ; cvlan vid=2023
s2:actions = del cvlan; add after eth cvlan_new vid=1001 ; send ifA
