from debian:trixie-slim
RUN apt -qq -y update && \
  apt -qq -y install --no-install-recommends \
  build-essential \
  clang \
  cmake \
  gcc \
  iproute2 \
  iptables \
  iputils-ping \
  libyaml-tiny-perl \
  mininet \
  perl \
  psmisc \
  python3-pyroute2 \
  python3-regex \
  python3-scapy \
  strace  \
  tshark \
  valgrind
