# The [interfaces] section can be used to define the ingress/egress interfaces
# and their streams. Its format is the following:
# iface_custom_name = type param1=value1 param2=value2
# For ingress interfaces, the must have a stream list.
# This can be defined as iface_custom_name:streams = stream1 stream2 stream3...
# An ingress packet will be triet to match by each stream (in the order they defined in the list)
# If no match, it will be dropped

[interfaces]
# uni is the name we refer to this interfaces in the rest of the config file
# eth is the type and implemented as a raw layer 2 packet-socket
# For eth type, only the iface parameter required, which is the name if the name of a Linux network interface
# uni:streams is the list of the streams tried to match for ingress packets, currently only 1 stream
#   given for each interface
uni = eth iface=swp2
uni:streams = stream_uni
nni1 = eth iface=swp0
nni1:streams = stream_nni1
nni2 = eth iface=swp1
nni2:streams = stream_nni2


# In the [objects] section we have the stateful packet processing information.
# These object can be used as parameters of actions in the pipelines.
# The same object can be used in multiple pipelines as well.
# Every object has a type, it is possible to define multiple action with the same type,
# however they has to hav different names e.g.
# seqgen1 = SeqGen
# seqgen2 = SeqGen
# another_seqgen = SeqGen
# They have their own internal states
# The formet looks like the following:
# obj_name = type param1=val1 param2=val2...
# (the type is mandatory, parameters might have or not, depends on the action)
[objects]
# SeqGen generate seqence number every time when it executed in the pipeline.
# This sequence number will be set to that packet, but NOT WRITTEN INTO ANY HEADER by default.
# The rationale behind this behavior: a sequence number can be used in different parts of the pipeline,
# and for both TSN R-tag and DetNet d-CW, its format depends on the heade used. Also one can generate a
# seqence number, but that used on different branches of the pipeline.
# For example, if a pipeline have 3 branches, each with different encapsulation, it only makes sense to
# generate the sequence number early, since if they generated on the branches, each branch will increase the
# internal state sequence number, resulting undefined behavior
seq_gen = SeqGen InitSeqStart=0
# SeqRcvy is used at the elimination side. Its working with sequence number of the packet, so before
# a SeqRcvy object used in the action pipeline, the packet MUST HAVE SEQUENCE NUMBER.
# This will be obtained from the sequenced header like rtag or dcw with the "readseq HEADERNAME" action.
# SeqRcvy drop every replica of the packet, except the first one.
seqrcvy = SeqRcvy

# Here the [streams] defined, they each have three set of settings as definition:
# :packet - header structure (until we interested)
# :match - matching on header fields for packet identification. Multiple headers and fields can be matched
# :actions - pipeline definition. List of actions executed sequentially.
# The actions in the list separated by commas, they might have parameters as well.
# Some actions can use objects as their parameters and some objects are implicitly recognized as actions
# like seq_gen or seqrcvy below. They can be written as "seqgen seq_gen" and "eliminate seqrcvy" as well.
[streams]
stream_uni:packet = eth, cvlan
stream_uni:match = cvlan vid=0
stream_uni:actions = seq_gen, after cvlan add rtag, writeseq rtag, replicate tx_nni1 tx_nni2

# The "replicate" action can be used to branch the pipeline. It copies the packet and execute
# the list of pipelines on the copies - one pipeline on each copy
# In the current example, "replicate tx_nni1 tx_nni2" will create a copy and the original packet
# continue its way on the tx_nni1 pipeline and the copy on the tx_nni2 pipeline.
# There can be more then two pipelines.
# Although the "send" action usually the end of the pipeline, thats optional, other actions
# can be defined after the send action as well and they will executed as usual
tx_nni1 = edit cvlan.vid=100, send nni1
tx_nni2 = edit cvlan.vid=200, send nni2

# The eliminate action (the seqrcvy in the current pipeline)
# used to execute the seq recovery algorithm on the sequence numbered packets.
# The eliminate action have one mandatory paramter: the pipeline to execute.
# If the packet not dropped (the first among many packets from the same sequence number)
# will continue the processing on the nni_pipe.
# This is similar to the replicate, however it used to merge pipelines instead of branching.

stream_nni1:packet = eth, cvlan, rtag
stream_nni1:match = cvlan vid=100
stream_nni1:actions = readseq rtag, seqrcvy nni_pipe

stream_nni2:packet = eth, cvlan, rtag
stream_nni2:match = cvlan vid=200
stream_nni2:actions = readseq rtag, seqrcvy nni_pipe

nni_pipe = del rtag, del cvlan, send uni
