# on both gateways: radvd -C ./radvd.conf -m stderr -n -p ./radvd_gateway1.pid

interface swp1 {
    AdvSendAdvert on;
    MinRtrAdvInterval 3;
    MaxRtrAdvInterval 10;
    prefix ::/64 {
        AdvOnLink on; # default
        AdvAutonomous on; # default
        AdvRouterAddr on;
        AdvValidLifetime 20;
        AdvPreferredLifetime 20;
    };
};
