#!/usr/bin/bash

AGGREGATE=/tmp/dnt.md

# getting started scenarios
declare -a getting_started=(
    "tsn"
    "tsn_over_detnet"
    "ip_over_detnet"
    "ladder"
    "dynip"
    "oam"
    "mask"
    "notification"
    "2R-2E"
    "srv6"
)

# documentations
declare -a doc_topics=(
    "logging"
    "oam"
    "notification"
    "srv6"
    "config_format"
    "protocols" #generated by protocolfields.pl
)

declare -a dev_topics=(
    "architecture"
    "value_transfer"
    "style"
)

VER_MARJOR=$(grep -oP 'VERSION_MAJOR \K\d+' version.h)
VER_MINOR=$(grep -oP 'VERSION_MINOR \K\d+' version.h)

# how to change the font size for teletype:
#   redefine \texttt for the inline teletype text (LaTeX core)
#   verbatim@font sets for block environments without any special (package verbatim)
#   FV@FontSize sets for block environments with line/page breaks (package fancyvrb)

#TODO can we get rid of the gaps between rows in the teletype figures?
#   TODO none of the followings work
#  \AtBeginEnvironment{verbatim}{\setlength{\lineskip}{0pt}}
#  \fvset{formatcom=\setlength{\lineskip}{0pt}}
#  \usepackage{setspace}
#  \fvset{formatcom=\singlespacing}

preamble="
---
title: DNT v${VER_MARJOR}.${VER_MINOR} documentation
urlcolor: blue
header-includes: |
  \usepackage{fancyhdr}
  \usepackage{verbatim}
  \usepackage{fancyvrb}
  \usepackage{fvextra}
  \fvset{breaklines=true}
  \renewcommand*{\texttt}[1]{{\small{\ttfamily #1}}}
  \makeatletter
  \\def\verbatim@font{\normalfont\ttfamily\small\hyphenchar\font\m@ne\@noligs}
  \\def\FV@FontSize{\small}
  \makeatother
  \fvset{formatcom=\setlength{\parskip}{0pt}}
...

"

create_pdf() {
  # collect getting started readme paths
  FILES="README.md getting_started/README.md"
  for scenario in "${getting_started[@]}"
  do
    FILES="${FILES} getting_started/scenario_${scenario}/README.md"
  done

  # add paths for user documents
  for docfile in "${doc_topics[@]}"
  do
    FILES="${FILES} doc/${docfile}.md"
  done

  # add paths for dev documents
  for docfile in "${dev_topics[@]}"
  do
    FILES="${FILES} doc/dev/${docfile}.md"
  done

  # aggregate all doc files to one
  echo "$preamble" > ${AGGREGATE}
  for doc in ${FILES}
  do
    echo ${doc}
    echo "" >> ${AGGREGATE}
    # inline LaTeX for new page before each section
    echo "\newpage{}" >> ${AGGREGATE}
    # inline LaTeX for more document structuring
    if [ ${doc} == 'getting_started/README.md' ] ; then
        echo "\part{Getting Started}\newpage{}" >> ${AGGREGATE}
    fi
    if [ ${doc} == 'doc/logging.md' ] ; then
        echo "\part{User Manual}\newpage{}" >> ${AGGREGATE}
    fi
    if [ ${doc} == 'doc/dev/architecture.md' ] ; then
        echo "\part{Developer Manual}\newpage{}" >> ${AGGREGATE}
    fi
    cat ${doc} >> ${AGGREGATE}
    echo "" >> ${AGGREGATE}
  done

  # remove badges (they are for gitlab)
  sed -i "/badges/d" $AGGREGATE

  # generate the PDF with pandoc and texlive-xetex
	pandoc \
    --toc \
    --pdf-engine=xelatex \
    -V 'monofontoptions: Color=0070c0' \
		-V monofont="Noto Sans Mono" \
    -V fontsize=12pt -V geometry:margin=1.5cm $AGGREGATE -o readme.pdf
}

create_pdf
