#!/usr/bin/bash

# getting started scenarios
declare -a getting_started=(
    "tsn"
    "tsn_over_detnet"
    "ip_over_detnet"
    "oam"
    "mask"
    "dynip"
    "srv6"
    "notification"
    "2R-2E"
)

# documentations
declare -a doc_topics=(
    "logging"
    "oam"
    "notification"
    "srv6"
    "config_format"
    "protocols" #generated by protocolfields.pl
)

VER_MARJOR=$(grep -oP 'VERSION_MAJOR \K\d+' version.h)
VER_MINOR=$(grep -oP 'VERSION_MINOR \K\d+' version.h)

# Markdown has no newpage directive.
# We need to call out for Latex to insert pagebreaks
preamble="
---
title: R2DTWO v${VER_MARJOR}.${VER_MINOR} documentation
urlcolor: blue
header-includes: |
  \usepackage{fancyhdr}
  \usepackage{fvextra}
  \fvset{breaklines=true}
include-before:
- '\`\newpage{}\`{=latex}'
---

"

create_pdf() {

  AGGREGATE=/tmp/r2dtwo.md

  # collect getting started readme paths
  FILES="README.md getting_started/README.md"
  for scenario in "${getting_started[@]}"
  do
    FILES="${FILES} getting_started/scenario_${scenario}/README.md"
  done

  # add paths for other documents
  for docfile in "${doc_topics[@]}"
  do
    FILES="${FILES} doc/${docfile}.md"
  done

  # aggregate all doc files to one
  echo "$preamble" > ${AGGREGATE}
  for doc in ${FILES}
  do
    echo ${doc}
    echo "" >> ${AGGREGATE}
    echo "\newpage{}" >> ${AGGREGATE}
    cat ${doc} >> ${AGGREGATE}
    echo "" >> ${AGGREGATE}
  done

  # remove badges (they are for gitlab)
  sed -i "/badges/d" $AGGREGATE

  # generate the PDF with pandoc and texlive-xetex
	pandoc \
    --toc \
    --pdf-engine=xelatex \
    -V 'monofontoptions: Color=0070c0,Scale=0.6' \
		-V monofont="Noto Sans Mono" \
    -V fontsize=12pt -V geometry:margin=1.5cm $AGGREGATE -o readme.pdf
}

create_pdf
