[ interfaces ]

uni_in = eth iface=ethDE
uni_out = ip iface=ethDE

nni4_out = udp-out iface=ethDC dstip=10.0.2.2
nni4_in = udp-in iface=ethDC ipv=4 senders=10.0.2.2,nni4_out,fd02::2,nni4_out
nni6_out = udp-out iface=ethDC dstip=fd02::2
nni6_in = udp-in iface=ethDC ipv=6 senders=fd02::2,nni6_out,10.0.2.2,nni6_out

uni_in:streams = in4 in6
nni4_in:streams = tun4
nni6_in:streams = tun6

ifCmd = oam_cmd
#ifReturn = oam ip=fd03::4

[ objects ]

seqgen4 = SeqGen
seqgen6 = SeqGen

secrcvy4 = SeqRcvy frerSeqRcvyHistoryLength=16
secrcvy6 = SeqRcvy frerSeqRcvyHistoryLength=16

[ streams ]

in4:packet = eth, cvlan, ipv4
in4:match = cvlan tpid=ipv4, ipv4 dst=10.0.1.0/24
in4:actions = del eth, del cvlan, seqgen4, before ipv4 add dcw, before dcw add mpls bos=yes ttl=3, edit mpls.label=400, send nni4_out

in6:packet = eth, cvlan, ipv6
in6:match = cvlan tpid=ipv6, ipv6 dst=fd01::/64
in6:actions = del eth, del cvlan, seqgen6, before ipv6 add dcw, before dcw add mpls bos=yes ttl=3, edit mpls.label=600, send nni6_out

tun4:packet = mpls, dcw, ipv4
tun4:match = mpls label=400
tun4:actions = readseq dcw, secrcvy4 to_uni

tun6:packet = mpls, dcw, ipv6
tun6:match = mpls label=600
tun6:actions = readseq dcw, secrcvy6 to_uni

to_uni = del mpls, del dcw, send uni_out
