# on nc: radvd -C ./radvdC.conf -m stderr -n
# this will autoconfigure address on ethDC

interface ethCD {
    AdvSendAdvert on;
    MinRtrAdvInterval 3;
    MaxRtrAdvInterval 10;
    prefix fd03::/64 {
        AdvOnLink on; # default
        AdvAutonomous on; # default
        AdvRouterAddr on;
    };
};

