# on nc: radvd -C ./radvdCnoaddr.conf -m stderr -n
# this will advertise the gateway without configuring address on ethDC

interface ethCD {
    AdvSendAdvert on;
    AdvManagedFlag on;
    MinRtrAdvInterval 3;
    MaxRtrAdvInterval 10;
    prefix ::/64 {
        AdvOnLink on; # default
        AdvAutonomous off;
        AdvRouterAddr on;
        AdvValidLifetime 20;
        AdvPreferredLifetime 20;
    };
};

