[interfaces]

uni_in = eth iface=r2eth1
uni_out = ip iface=swp2

nni_in0 = udp-in iface=swp0 ipv=4
nni_in1 = udp-in iface=swp1 ipv=4
nni_out0 = udp-out iface=swp0 dstip=192.168.55.2
nni_out1 = udp-out iface=swp1 dstip=192.168.66.2

uni_in:streams = compound
nni_in0:streams = pw1
nni_in1:streams = pw2

cmd0 = oam_cmd ip=172.16.0.1 port=8000
oam0 = oam ip=172.16.0.1 port=6634

[objects]

gen = SeqGen
;pef = SeqRcvy frerSeqRcvyHistoryLength=16 AutoMIP=5
;prf = Replicate AutoMIP=5
pef = SeqRcvy frerSeqRcvyHistoryLength=16
prf = Replicate

[streams]

compound:packet = eth, cvlan, ipv4
compound:match = cvlan tpid=ipv4, ipv4 src=10.0.100.0/24
compound:actions = gen, del eth, del cvlan, before ipv4 add dcw, before dcw add mpls bos=1, prf prf-member1 prf-member2

prf-member1 = edit mpls.label=1000 mpls.bos=1, send nni_out0
prf-member2 = edit mpls.label=2000 mpls.bos=1, send nni_out1

pw1:packet = mpls, dcw, ipv4
pw1:match = mpls label=1000
pw1:actions = readseq dcw, pef compound

pw2:packet = mpls, dcw, ipv4
pw2:match = mpls label=2000
pw2:actions = readseq dcw, pef compound

compound = del mpls, del dcw, send uni_out
