[interfaces]

uni_in = eth iface=swp2
; uni_in = eth iface=r2eth1 ;use this after configure_tc command
uni_out = ip iface=swp2

v4nni_in0 = udp-in iface=swp0 ipv=4
v6nni_in0 = udp-in iface=swp0 ipv=6
v4nni_in1 = udp-in iface=swp1 ipv=4
v6nni_in1 = udp-in iface=swp1 ipv=6

v4nni_out0 = udp-out iface=swp0 dstip=192.168.55.1
v6nni_out0 = udp-out iface=swp0 dstip=fc0a::1
v4nni_out1 = udp-out iface=swp1 dstip=192.168.66.1
v6nni_out1 = udp-out iface=swp1 dstip=fc0b::1

uni_in:streams = compound4 compound6
v4nni_in0:streams = pw4
v4nni_in1:streams = pw4
v6nni_in0:streams = pw6
v6nni_in1:streams = pw6

[objects]

gen4 = SeqGen
gen6 = SeqGen

pef4 = SeqRcvy frerSeqRcvyHistoryLength=16
pef6 = SeqRcvy frerSeqRcvyHistoryLength=16

prf4 = Replicate
prf6 = Replicate

[streams]

compound4:packet = eth, cvlan, ipv4
compound4:match = cvlan tpid=ipv4, ipv4 src=10.0.200.0/24
compound4:actions = gen4, del eth, del cvlan, before ipv4 add dcw, before dcw add mpls bos=1, prf4 prf4-member1 prf4-member2

prf4-member1 = edit mpls.label=400 mpls.bos=1, send v4nni_out0
prf4-member2 = edit mpls.label=400 mpls.bos=1, send v4nni_out1

compound6:packet = eth, cvlan, ipv6
compound6:match = cvlan tpid=ipv6, ipv6 src=2002::/64
compound6:actions = gen6, del eth, del cvlan, before ipv6 add dcw, before dcw add mpls bos=1, prf6 prf6-member1 prf6-member2

prf6-member1 = edit mpls.label=600 mpls.bos=1, send v6nni_out0
prf6-member2 = edit mpls.label=600 mpls.bos=1, send v6nni_out1

pw4:packet = mpls, dcw, ipv4
pw4:match = mpls label=400
pw4:actions = readseq dcw, pef4 compound

pw6:packet = mpls, dcw, ipv6
pw6:match = mpls label=600
pw6:actions = readseq dcw, pef6 compound

compound = del mpls, del dcw, send uni_out
