# config to emulate r1d1
# run this on nb of quicktest

[interfaces]

ifBA = eth iface=ethBA
ifBA:streams = fromBA
ifBC = eth iface=ethBC
ifBC:streams = fromBC

[streams]

fromBA:packet = eth, cvlan
fromBA:match =
fromBA:actions = del cvlan, send ifBC

fromBC:packet = eth, cvlan
fromBC:match =
fromBC:actions = del cvlan, send ifBA
