
[interfaces]

ifA = eth iface=ethBA
ifA:streams = sa
#ifCout = udp-out iface=ethBC dstip=10.0.2.3
ifCout = udp-out iface=ethBC dstip=fd02::3 srcport=663
ifCin  = udp-in iface=ethBC ipv=6
ifCin:streams = su

ifCmd = oam_cmd oam_cmd_ip=0.0.0.0
ifReturn = oam oam_ip=fd02::2

[objects]

sgen = SeqGen InitSeqStart=5

[streams]

sa:packet = eth, cvlan
sa:match = cvlan vid=1001
sa:actions = sgen, before eth add dcw, edit dcw.resv=0x0000, before dcw add mpls label=101 bos=1 ttl=1, mep-start startB 2, send ifCout

su:packet = mpls, dcw, eth, cvlan
su:match = mpls label=220
su:actions = del mpls, del dcw, edit cvlan.vid=1001, send ifA
