
[interfaces]

#ifDummy = eth iface=ethdummy
#ifDummy:streams = sdummy

ifD = eth iface=ethCD
ifD:streams = sd
ifBout = udp-out iface=ethCB dstip=ipv6
ifBin  = udp-in iface=ethCB ipv=4 senders=fd02::2,ifCout
ifBin:streams = su

if_int = internal
if_int:streams = si
#if_int:streams = 

ifCmd = oam_cmd
ifReturn = oam ip=fd02::3

[objects]

sgen = SeqGen InitSeqStart=6

[streams]

sd:packet = eth, cvlan
sd:match = cvlan vid=3210
sd:actions = sgen, before eth add dcw, before dcw add mpls label=220 bos=1 ttl=1, send ifBout

su:packet = mpls, dcw
su:match = mpls label=101
su:actions = mip quickmip 2, del mpls, del dcw, send if_int

si:packet = eth, cvlan
si:match = 
si:actions = edit cvlan.vid=3210, send ifD,
#send ifDummy

sdummy:packet = eth
sdummy:match =
sdummy:actions = drop
