
[interfaces]

ifD = eth iface=ethCD
ifD:streams = sd
#ifBout = udp-out iface=ethCB dstip=10.0.2.2
ifBout = udp-out iface=ethCB dstip=fd02::2
ifBin  = udp-in iface=ethCB ipv=6
ifBin:streams = su

if_int = internal
if_int:streams = si

[streams]

sd:packet = eth, cvlan
sd:match = cvlan vid=3210
sd:actions = before eth add dcw, before dcw add mpls label=220 bos=1, send ifBout

su:packet = mpls, dcw
su:match = mpls label=101
su:actions = del mpls, del dcw, send if_int

si:packet = eth, cvlan
si:match = 
si:actions = edit cvlan.vid=3210, send ifD
