
[interfaces]

ifA = eth iface=ethBA
ifA:streams = s1
ifC = eth iface=ethBC
ifC:streams = s2

ifCtrl = oam_cmd
ifOam = oam ip=fd02::2

[objects]

sgen1 = SeqGen InitSeqStart=3
srcvy1 = SeqRcvy
prf1 = Replicate

[streams]

s1:packet = eth, cvlan          ; now we can have comments at the end
s1:match = cvlan vid=1001       # both start characters are supported
s1:actions = edit cvlan.vid=2023, send ifC, sgen1, before cvlan add rtag, replicate prf1 alice bob
#send ifC, add before cvlan svlan_new pcp=3 vid=2000 , add after cvlan rtag seq=0x0800abcd , edit cvlan.pcp=2, del cvlan , send ifC

s2:packet = eth , cvlan
s2:match = cvlan vid=2023, eth ethertype=cvlan
s2:actions = del cvlan, after eth add cvlan vid=1001 pcp=2, send ifA, edit eth.ethertype=svlan, send ifA

alice = edit cvlan.pcp=2, before cvlan add svlan vid=20 , send ifC, diane
bob = edit cvlan.pcp=3, after eth add svlan vid=30, jump charlie
charlie = readseq rtag, srcvy1 charlie_cont
charlie_cont = send ifC, after cvlan add mpls label=102030 bos=1 ttl=32, send ifC
diane = edit eth.smac=ifC.mac, after rtag add ttag, send ifC
